name: YMenu
api: ["1.0.0"]
version: "1.0.0"
load: POSTWORLD
main: yxmingy.ymenu.Main
commands:
 menu:
  description: "召唤菜单"
  usage: "/menu [菜单名]"
  permission: yxmingy.command.menu
permissions:
 yxmingy.command.menu: 
  default: true
